//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MALM.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MALM.Localization.LStrings", typeof(LStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Master Key or AddressBook file corrupted!.
        /// </summary>
        internal static string E_ENCRYPT_FAILED {
            get {
                return ResourceManager.GetString("E_ENCRYPT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add new item &apos;{0}&apos;!.
        /// </summary>
        internal static string E_FAILED_TO_ADD_ITEM {
            get {
                return ResourceManager.GetString("E_FAILED_TO_ADD_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too old, need update!.
        /// </summary>
        internal static string E_FW_TOO_OLD {
            get {
                return ResourceManager.GetString("E_FW_TOO_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to Mikrotik!.
        /// </summary>
        internal static string E_MIKROTIK_CONNECTION_FAILED {
            get {
                return ResourceManager.GetString("E_MIKROTIK_CONNECTION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse OUI database!.
        /// </summary>
        internal static string E_OUI_FAILED_TO_PARSE_OUI_CONTENT {
            get {
                return ResourceManager.GetString("E_OUI_FAILED_TO_PARSE_OUI_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required network permission!.
        /// </summary>
        internal static string E_PERMISSION_NETWORK_ERROR {
            get {
                return ResourceManager.GetString("E_PERMISSION_NETWORK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute!.
        /// </summary>
        internal static string E_TITLE_DEFAULT {
            get {
                return ResourceManager.GetString("E_TITLE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        internal static string E_TITLE_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("E_TITLE_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string L_ADD {
            get {
                return ResourceManager.GetString("L_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        internal static string L_APP_EXIT {
            get {
                return ResourceManager.GetString("L_APP_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string L_APPLY {
            get {
                return ResourceManager.GetString("L_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or select a sample from list below:.
        /// </summary>
        internal static string L_ATR_SAMPLE_GROUP {
            get {
                return ResourceManager.GetString("L_ATR_SAMPLE_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string L_CANCEL {
            get {
                return ResourceManager.GetString("L_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string L_COMMENT {
            get {
                return ResourceManager.GetString("L_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string L_CONNECT {
            get {
                return ResourceManager.GetString("L_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}....
        /// </summary>
        internal static string L_CONNECTING_TO {
            get {
                return ResourceManager.GetString("L_CONNECTING_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string L_CREATED {
            get {
                return ResourceManager.GetString("L_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string L_DEFAULT {
            get {
                return ResourceManager.GetString("L_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string L_DELETE {
            get {
                return ResourceManager.GetString("L_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string L_DEVICE_ADDRESS {
            get {
                return ResourceManager.GetString("L_DEVICE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        internal static string L_DEVICE_BOARD {
            get {
                return ResourceManager.GetString("L_DEVICE_BOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string L_DEVICE_CPU {
            get {
                return ResourceManager.GetString("L_DEVICE_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        internal static string L_DEVICE_CPU_INFO {
            get {
                return ResourceManager.GetString("L_DEVICE_CPU_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string L_DEVICE_GROUP {
            get {
                return ResourceManager.GetString("L_DEVICE_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string L_DEVICE_HDD {
            get {
                return ResourceManager.GetString("L_DEVICE_HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad blocks.
        /// </summary>
        internal static string L_DEVICE_HDD_BAD_BLOCKS {
            get {
                return ResourceManager.GetString("L_DEVICE_HDD_BAD_BLOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string L_DEVICE_PASSWORD {
            get {
                return ResourceManager.GetString("L_DEVICE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string L_DEVICE_PORT {
            get {
                return ResourceManager.GetString("L_DEVICE_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up time.
        /// </summary>
        internal static string L_DEVICE_UPTIME {
            get {
                return ResourceManager.GetString("L_DEVICE_UPTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string L_DEVICE_USER {
            get {
                return ResourceManager.GetString("L_DEVICE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices List.
        /// </summary>
        internal static string L_DEVICES_LIST {
            get {
                return ResourceManager.GetString("L_DEVICES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Devices List.
        /// </summary>
        internal static string L_DEVICES_LIST_EDITOR {
            get {
                return ResourceManager.GetString("L_DEVICES_LIST_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string L_DISABLE {
            get {
                return ResourceManager.GetString("L_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string L_EDIT {
            get {
                return ResourceManager.GetString("L_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string L_EMPTY_GROUP_NAME {
            get {
                return ResourceManager.GetString("L_EMPTY_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string L_ENABLE {
            get {
                return ResourceManager.GetString("L_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter .
        /// </summary>
        internal static string L_ENTER_ {
            get {
                return ResourceManager.GetString("L_ENTER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string L_FILTER {
            get {
                return ResourceManager.GetString("L_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rows were found with &apos;{0}&apos;..
        /// </summary>
        internal static string L_FILTERED_DATA_EMPTY {
            get {
                return ResourceManager.GetString("L_FILTERED_DATA_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering data....
        /// </summary>
        internal static string L_FILTERING_DATA {
            get {
                return ResourceManager.GetString("L_FILTERING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string L_FREE {
            get {
                return ResourceManager.GetString("L_FREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string L_ID {
            get {
                return ResourceManager.GetString("L_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string L_INITIALIZING {
            get {
                return ResourceManager.GetString("L_INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave empty for default.
        /// </summary>
        internal static string L_LEAVE_EMPTY_FOR_DEFAULT {
            get {
                return ResourceManager.GetString("L_LEAVE_EMPTY_FOR_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List is empty.
        /// </summary>
        internal static string L_LIST_IS_EMPTY {
            get {
                return ResourceManager.GetString("L_LIST_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Password.
        /// </summary>
        internal static string L_MASTER_KEY {
            get {
                return ResourceManager.GetString("L_MASTER_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember and don&apos;t ask.
        /// </summary>
        internal static string L_MASTER_KEY_CACHING {
            get {
                return ResourceManager.GetString("L_MASTER_KEY_CACHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask (use biometrics).
        /// </summary>
        internal static string L_MASTER_KEY_CACHING_USE_BIO {
            get {
                return ResourceManager.GetString("L_MASTER_KEY_CACHING_USE_BIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        internal static string L_MEMORY {
            get {
                return ResourceManager.GetString("L_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikrotik List (Group).
        /// </summary>
        internal static string L_MIKROTIK_ADDRESS_LIST {
            get {
                return ResourceManager.GetString("L_MIKROTIK_ADDRESS_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting {0}....
        /// </summary>
        internal static string L_MIKROTIK_CONNECTION_INPROGRESS {
            get {
                return ResourceManager.GetString("L_MIKROTIK_CONNECTION_INPROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new item to Mikrotik AddressList.
        /// </summary>
        internal static string L_MK_ADDRESS_LIST_EDITOR {
            get {
                return ResourceManager.GetString("L_MK_ADDRESS_LIST_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New .
        /// </summary>
        internal static string L_NEW_ {
            get {
                return ResourceManager.GetString("L_NEW_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New element will be created in disabled state for safety!.
        /// </summary>
        internal static string L_NEW_ELEMENT_WILL_BE_DISABLED {
            get {
                return ResourceManager.GetString("L_NEW_ELEMENT_WILL_BE_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string L_NO {
            get {
                return ResourceManager.GetString("L_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string L_OK {
            get {
                return ResourceManager.GetString("L_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quering data....
        /// </summary>
        internal static string L_QUERING_DATA {
            get {
                return ResourceManager.GetString("L_QUERING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string L_REFRESH {
            get {
                return ResourceManager.GetString("L_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter.
        /// </summary>
        internal static string L_REPEAT {
            get {
                return ResourceManager.GetString("L_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string L_SAVE {
            get {
                return ResourceManager.GetString("L_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string L_SET {
            get {
                return ResourceManager.GetString("L_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since reboot.
        /// </summary>
        internal static string L_SINCE_REBOOT {
            get {
                return ResourceManager.GetString("L_SINCE_REBOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string L_TOTAL {
            get {
                return ResourceManager.GetString("L_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string L_VERSION {
            get {
                return ResourceManager.GetString("L_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This programm uses icons from &apos;{0}.
        /// </summary>
        internal static string L_WE_USE_FREE_ICONS {
            get {
                return ResourceManager.GetString("L_WE_USE_FREE_ICONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write sect..
        /// </summary>
        internal static string L_WRITE_SECT {
            get {
                return ResourceManager.GetString("L_WRITE_SECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string L_YES {
            get {
                return ResourceManager.GetString("L_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete record &apos;{0}&apos;?.
        /// </summary>
        internal static string Q_ADDRESSBOOK_DELETE_RECORD {
            get {
                return ResourceManager.GetString("Q_ADDRESSBOOK_DELETE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication required.
        /// </summary>
        internal static string Q_MASTERKEY_BIO_REQ {
            get {
                return ResourceManager.GetString("Q_MASTERKEY_BIO_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm login.
        /// </summary>
        internal static string Q_MASTERKEY_BIO_REQ_2 {
            get {
                return ResourceManager.GetString("Q_MASTERKEY_BIO_REQ_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use PIN.
        /// </summary>
        internal static string Q_MASTERKEY_BIO_USE_PIN {
            get {
                return ResourceManager.GetString("Q_MASTERKEY_BIO_USE_PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A forgotten master password cannot be recovered, it is not saved anywhere. You can reset it by setting a new one, but the data (address book) encrypted with the old key will be lost.||Reset the master password?.
        /// </summary>
        internal static string Q_RESET_MASTER_KEY {
            get {
                return ResourceManager.GetString("Q_RESET_MASTER_KEY", resourceCulture);
            }
        }
    }
}
